'use client';

import { useSSE } from '@/hooks/use-sse';
import { useAppStore } from '@/lib/store';
import { Loader2, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { useState, useEffect } from 'react';

export function AIReport({ repoPath }: { repoPath: string }) {
  const [generateUrl, setGenerateUrl] = useState<string | null>(null);
  const [requestedRepoPath, setRequestedRepoPath] = useState<string | null>(null);
  const streamUrl = requestedRepoPath === repoPath ? generateUrl : null;
  const { text, loading, error } = useSSE(streamUrl);
  
  const aiReportText = useAppStore(s => s.aiReportText);
  const setAiReportText = useAppStore(s => s.setAiReportText);

  useEffect(() => {
    if (text) setAiReportText(text);
  }, [text, setAiReportText]);

  const hasRequestedCurrentRepo = requestedRepoPath === repoPath && Boolean(generateUrl);
  const displayReportText = text || (requestedRepoPath === repoPath ? aiReportText : '');

  const handleGenerate = () => {
    setAiReportText('');
    setRequestedRepoPath(repoPath);
    setGenerateUrl(`/api/report/stream?repo_path=${encodeURIComponent(repoPath)}&t=${Date.now()}`);
  };

  return (
    <div className="bg-white shadow-sm border border-slate-200 p-8 rounded-3xl max-w-4xl mx-auto">
      <div className="flex items-center gap-3 mb-8 pb-6 border-b border-slate-200">
        <div className="p-3 bg-blue-600/10 rounded-xl border border-blue-600/20">
          <Sparkles className="w-6 h-6 text-blue-600" />
        </div>
        <div>
          <h2 className="text-2xl font-bold">Executive Health Report</h2>
          <p className="text-slate-500 text-sm">Generated by Groq (Llama 3) using live repository data</p>
        </div>
      </div>

      <div className="prose prose-slate prose-blue max-w-none font-sans">
        {error ? (
          <div className="text-red-400 p-4 bg-red-500/10 rounded-xl border border-red-500/20">
            {error}
          </div>
        ) : (
          <div className="space-y-6 text-slate-700 leading-relaxed">
            {!hasRequestedCurrentRepo && !displayReportText && (
               <div className="text-center py-12">
                 <button onClick={handleGenerate} className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-medium transition-colors shadow-sm">
                   <Sparkles className="w-5 h-5" />
                   Generate Executive Report
                 </button>
                 <p className="text-sm text-slate-400 mt-4">This will use your Groq API credits.</p>
               </div>
            )}
            
            {displayReportText ? (
              <ReactMarkdown>{displayReportText}</ReactMarkdown>
            ) : loading ? (
              <div className="flex items-center gap-3 text-slate-400">
                <Loader2 className="w-5 h-5 animate-spin" />
                Analyzing data and generating narrative...
              </div>
            ) : null}
            
            {loading && text && (
              <span className="inline-block w-2 h-4 bg-blue-600 animate-pulse ml-1 align-middle" />
            )}
            
            {!loading && displayReportText ? (
               <div className="mt-8 pt-6 border-t border-slate-100 italic">
                 <button onClick={handleGenerate} className="text-sm text-blue-600 hover:text-blue-700 font-medium">
                   Regenerate Report
                 </button>
               </div>
            ) : null}
          </div>
        )}
      </div>
    </div>
  );
}
